sonar.projectKey=laboratorio-7
sonar.projectName=Laboratorio 7
sonar.projectVersion=1.0

sonar.sources=backend-springboot/src/main/java,frontend-reactjs/src
sonar.tests=backend-springboot/src/test/java

sonar.java.binaries=backend-springboot/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend-springboot/target/site/jacoco/jacoco.xml
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/target/**,**/build/**,**/dist/**,**/.git/**

sonar.host.url=http://localhost:9000