-- =======================
-- Flyway Init - V1
-- Create Project, Task Tables
-- =======================

CREATE TABLE IF NOT EXISTS project (
<<<<<<< Updated upstream
    id BIGSERIAL PRIMARY KEY,
=======
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
>>>>>>> Stashed changes
    name VARCHAR(255) NOT NULL,
    description CLOB
);

CREATE TABLE IF NOT EXISTS task (
<<<<<<< Updated upstream
    id BIGSERIAL PRIMARY KEY,
=======
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
>>>>>>> Stashed changes
    title VARCHAR(255) NOT NULL,
    description CLOB,
    status VARCHAR(20) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    project_id BIGINT REFERENCES project(id) ON DELETE CASCADE
);
